// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"time"
)

type Repository struct {
	Path          string    `json:"path"`
	Name          string    `json:"name"`
	GitDirty      bool      `json:"gitDirty"`
	GitBranch     string    `json:"gitBranch"`
	GitAction     string    `json:"gitAction"`
	GitCountLeft  int64     `json:"gitCountLeft"`
	GitCountRight int64     `json:"gitCountRight"`
	UsageCount    int64     `json:"usageCount"`
	UpdateTime    time.Time `json:"updateTime"`
}
