// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	DeleteRepository(ctx context.Context, path string) error
	IncRepoUsageCount(ctx context.Context, path string) error
	ListRepositories(ctx context.Context) ([]Repository, error)
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error
}

var _ Querier = (*Queries)(nil)
