// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package db

import (
	"context"
)

const deleteRepository = `-- name: DeleteRepository :exec
delete
from repositories
where path = ?
`

func (q *Queries) DeleteRepository(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteRepository, path)
	return err
}

const incRepoUsageCount = `-- name: IncRepoUsageCount :exec
update repositories
set usage_count = usage_count + 1,
    update_time = CURRENT_TIMESTAMP
where path = ?
`

func (q *Queries) IncRepoUsageCount(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, incRepoUsageCount, path)
	return err
}

const listRepositories = `-- name: ListRepositories :many
SELECT path, name, git_dirty, git_branch, git_action, usage_count, update_time
FROM repositories
order by usage_count desc, name
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.Path,
			&i.Name,
			&i.GitDirty,
			&i.GitBranch,
			&i.GitAction,
			&i.UsageCount,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepository = `-- name: UpsertRepository :exec
insert into repositories (path, name, git_branch, git_dirty, git_action)
values (@path, @name, @git_branch, @git_dirty, @git_action)
on conflict (path) do update set name        = @name,
                                 git_branch  = @git_branch,
                                 git_dirty   = @git_dirty,
                                 git_action  = @git_action,
                                 update_time = CURRENT_TIMESTAMP
`

type UpsertRepositoryParams struct {
	Path      string `json:"path"`
	Name      string `json:"name"`
	GitBranch string `json:"gitBranch"`
	GitDirty  bool   `json:"gitDirty"`
	GitAction string `json:"gitAction"`
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepository,
		arg.Path,
		arg.Name,
		arg.GitBranch,
		arg.GitDirty,
		arg.GitAction,
	)
	return err
}
